export const mockAccordionItems = [
  {
    title: "What is React?",
    content:
      "React is a JavaScript library for building user interfaces. It allows developers to create large web applications that can update and render efficiently with dynamic data.",
  },
  {
    title: "What is a Hook in React?",
    content:
      "Hooks are functions that let you use React features like state and lifecycle without writing a class. Common hooks include useState, useEffect, useContext, and more.",
  },
  {
    title: "How does useState work?",
    content:
      "useState is a Hook that lets you add state to functional components. It returns an array with the current state and a function to update it.",
  },
  {
    title: "What is the Virtual DOM?",
    content:
      "The Virtual DOM is an in-memory representation of the real DOM elements generated by React components before any changes are made to the page. It helps React efficiently update the DOM by diffing and batching updates.",
  },
  {
    title: "How do you pass props in React?",
    content:
      "Props are passed to components via HTML-like attributes. Inside the component, you can access them using the 'props' object or directly via destructuring.",
  },
];
